// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7JQJ6MmkcKF_ijnIUyahzmKER78FXZFw',
    appId: '1:817235117988:web:5d879779d999bce98ce331',
    messagingSenderId: '817235117988',
    projectId: 'jain-community-platform',
    authDomain: 'jain-community-platform.firebaseapp.com',
    storageBucket: 'jain-community-platform.firebasestorage.app',
    measurementId: 'G-F214MH5BB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRZWqh5vnz2kfMehXxEJeOTsAkVZ00b4',
    appId: '1:817235117988:android:d9f82206cb5680148ce331',
    messagingSenderId: '817235117988',
    projectId: 'jain-community-platform',
    storageBucket: 'jain-community-platform.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5sFltpT2RaTZKup0nV66U03s7OxRQ74',
    appId: '1:817235117988:ios:b1d74aa01dff66368ce331',
    messagingSenderId: '817235117988',
    projectId: 'jain-community-platform',
    storageBucket: 'jain-community-platform.firebasestorage.app',
    androidClientId: '817235117988-9tkgfqq3vn8c16rhfo0h30o20a8438cp.apps.googleusercontent.com',
    iosClientId: '817235117988-8aue6a3grtu1f3t6eoaaj9tjde05pufh.apps.googleusercontent.com',
    iosBundleId: 'com.nipun.jcp',
  );
}
