import 'package:flutter/material.dart';
import '../../../core/api/api_client.dart';
import '../../../core/api/api_exception.dart';

class FinanceConsolePage extends StatefulWidget {
  const FinanceConsolePage({required this.api, super.key});
  final ApiClient api;
  @override State<FinanceConsolePage> createState()=>_FinanceConsolePageState();
}
class _FinanceConsolePageState extends State<FinanceConsolePage>{
  final tabs=['Overview','Campaigns','Pledges','Payments','Expenses','Adjustments','Receipts','Reconciliation'];
  int tab=0; bool loading=true,busy=false; Object? error;
  Map<String,dynamic> summary={},recon={};
  List<Map<String,dynamic>> campaigns=[],pledges=[],payments=[],expenses=[],adjustments=[],receipts=[];
  @override void initState(){super.initState();load();}
  List<Map<String,dynamic>> maps(dynamic v)=>(v as List<dynamic>).whereType<Map>().map((x)=>Map<String,dynamic>.from(x)).toList();
  String s(dynamic v,[String d='—']){final x=v?.toString().trim()??'';return x.isEmpty?d:x;}
  String money(dynamic v){final n=v is num?v.toInt():int.tryParse('$v')??0;return '₹'+(n/100).toStringAsFixed(2);}
  String err(Object e)=>e is ApiException?e.message:'Request failed. Please retry.';
  Future<void> load()async{setState(() { loading = true; error = null; });try{final r=await Future.wait<dynamic>([widget.api.getObject('/api/giving/reports/summary'),widget.api.getObject('/api/giving/reports/reconciliation'),widget.api.getList('/api/giving/campaigns'),widget.api.getList('/api/giving/pledges'),widget.api.getList('/api/giving/payments'),widget.api.getList('/api/giving/expenses'),widget.api.getList('/api/giving/adjustments'),widget.api.getList('/api/giving/receipts')]);if(!mounted)return;setState(() { summary=Map<String,dynamic>.from(r[0] as Map); recon=Map<String,dynamic>.from(r[1] as Map); campaigns=maps(r[2]); pledges=maps(r[3]); payments=maps(r[4]); expenses=maps(r[5]); adjustments=maps(r[6]); receipts=maps(r[7]); loading=false; });}catch(e){if(mounted)setState(() { error=e; loading=false; });}}
  Future<String?> ask(String title,String label,{bool required=true,TextInputType keyboard=TextInputType.text})async{final c=TextEditingController();final k=GlobalKey<FormState>();final v=await showDialog<String>(context:context,builder:(ctx)=>AlertDialog(title:Text(title),content:Form(key:k,child:TextFormField(controller:c,keyboardType:keyboard,decoration:InputDecoration(labelText:label),validator:(v)=>required&&(v==null||v.trim().isEmpty)?'Required':null)),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:(){if(k.currentState?.validate()??false)Navigator.pop(ctx,c.text.trim());},child:const Text('Continue'))]));c.dispose();return v;}
  Future<String?> choose(String title,List<String> values)=>showDialog<String>(context:context,builder:(ctx)=>SimpleDialog(title:Text(title),children:[for(final v in values)SimpleDialogOption(onPressed:()=>Navigator.pop(ctx,v),child:Text(v.replaceAll('_',' ')))]));
  Future<void> run(Future<void> Function() fn,String success)async{setState(()=>busy=true);try{await fn();await load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(success)));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(err(e))));}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> createCampaign()async{final n=await ask('New campaign','Campaign name');if(n==null)return;final d=await ask('Campaign description','Description',required:false);if(d==null)return;await run(()async{await widget.api.post('/api/giving/campaigns',body:{'name':n,'description':d});},'Campaign created.');}
  Future<void> expense()async{final c=await ask('Record expense','Category');if(c==null)return;final d=await ask('Expense description','Description');if(d==null)return;final a=await ask('Expense amount','Amount in ₹',keyboard:const TextInputType.numberWithOptions(decimal:true));if(a==null)return;final n=double.tryParse(a);if(n==null||!n.isFinite||n<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid amount.')));return;}await run(()async{await widget.api.post('/api/giving/expenses',headers:{'Idempotency-Key':'finance-expense-'+DateTime.now().microsecondsSinceEpoch.toString()},body:{'category':c,'description':d,'amountPaise':(n*100).round()});},'Expense submitted for approval.');}
  Future<void> record(Map<String,dynamic> p)async{final a=await ask('Record payment','Amount in ₹',keyboard:const TextInputType.numberWithOptions(decimal:true));if(a==null)return;final n=double.tryParse(a);if(n==null||!n.isFinite||n<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid amount.')));return;}final m=await choose('Payment method',['CASH','UPI','BANK_TRANSFER','CHEQUE']);if(m==null)return;await run(()async{await widget.api.post('/api/giving/pledges/'+s(p['id'])+'/payments',headers:{'Idempotency-Key':'finance-payment-'+DateTime.now().microsecondsSinceEpoch.toString()},body:{'amountPaise':(n*100).round(),'method':m});},'Payment submitted for approval.');}
  Future<void> review(String path,{String? reason})async=>run(()async{await widget.api.post(path,body:reason==null?null:{'reason':reason});},'Decision saved.');
  Future<void> reject(String path)async{final r=await ask('Reject request','Reason for rejection');if(r!=null)await review(path,reason:r);}
  Future<void> adjust(Map<String,dynamic> p)async{final a=await ask('Refund or reversal','Amount in ₹',keyboard:const TextInputType.numberWithOptions(decimal:true));if(a==null)return;final n=double.tryParse(a);if(n==null||!n.isFinite||n<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid amount.')));return;}final r=await ask('Adjustment reason','Reason');if(r==null)return;final k=await choose('Adjustment type',['REFUND','REVERSAL']);if(k==null)return;await run(()async{await widget.api.post('/api/giving/payments/'+s(p['id'])+'/adjustments',headers:{'Idempotency-Key':'finance-adjustment-'+DateTime.now().microsecondsSinceEpoch.toString()},body:{'kind':k,'amountPaise':(n*100).round(),'reason':r});},'Adjustment submitted for approval.');}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Finance workspace'),actions:[IconButton(onPressed:loading||busy?null:load,tooltip:'Refresh',icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(err(error!)),FilledButton(onPressed:load,child:const Text('Retry'))])):Column(children:[if(busy)const LinearProgressIndicator(),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[for(var i=0;i<tabs.length;i++)Padding(padding:const EdgeInsets.all(4),child:ChoiceChip(label:Text(tabs[i]),selected:tab==i,onSelected:(_)=>setState(()=>tab=i)))])),Expanded(child:RefreshIndicator(onRefresh:load,child:content()))]));
  Widget content(){switch(tab){case 0:return overview();case 1:return campaignList();case 2:return pledgeList();case 3:return paymentList();case 4:return expenseList();case 5:return adjustmentList();case 6:return receiptList();default:return reconList();}}
  Widget header(String t,{Widget? action})=>Row(children:[Expanded(child:Text(t,style:Theme.of(context).textTheme.titleLarge)),if(action!=null)action]);
  Widget card(String t,String d,IconData i,{Widget? action})=>Card(margin:const EdgeInsets.only(bottom:8),child:ListTile(leading:CircleAvatar(child:Icon(i)),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w600)),subtitle:Text(d),isThreeLine:d.contains('\n'),trailing:action));
  Widget empty(String t)=>Padding(padding:const EdgeInsets.all(28),child:Center(child:Text(t)));
  Widget overview(){final t=Map<String,dynamic>.from((summary['totals'] as Map?)??const{});return ListView(padding:const EdgeInsets.all(16),children:[Text('Tenant finance overview',style:Theme.of(context).textTheme.headlineSmall),const Text('Only verified payments count as received. Reports are operational controls, not a statutory ledger.'),const SizedBox(height:12),for(final e in <String,dynamic>{'Pledged':t['pledgedAmountPaise'],'Received':t['receivedAmountPaise'],'Outstanding':t['outstandingAmountPaise'],'Net received':t['netReceivedAmountPaise']??recon['netAfterApprovedExpensesAndAdjustmentsPaise']}.entries)card(e.key,money(e.value),Icons.account_balance_wallet_outlined),header('Needs attention'),ListTile(title:const Text('Pending payments'),trailing:Text(payments.where((x)=>x['status']=='PENDING_APPROVAL').length.toString())),ListTile(title:const Text('Pending expenses'),trailing:Text(expenses.where((x)=>x['status']=='PENDING_APPROVAL').length.toString())),ListTile(title:const Text('Pending adjustments'),trailing:Text(adjustments.where((x)=>x['status']=='PENDING_APPROVAL').length.toString())]);}
  Widget campaignList()=>ListView(padding:const EdgeInsets.all(16),children:[header('Campaigns',action:FilledButton.icon(onPressed:busy?null:createCampaign,icon:const Icon(Icons.add),label:const Text('New'))),if(campaigns.isEmpty)empty('No campaigns found.')else for(final c in campaigns)card(s(c['name']),s(c['status'])+' • '+(c['targetAmountPaise']==null?'Target not set':'Target '+money(c['targetAmountPaise']))+'\n'+s(c['description'],'No description'),Icons.volunteer_activism,action:TextButton(onPressed:busy?null:()=>run(()async{final n=c['status']=='ACTIVE'?'CLOSED':'ACTIVE';await widget.api.patch('/api/giving/campaigns/'+s(c['id'])+'/status',body:{'status':n});},'Campaign updated.'),child:Text(c['status']=='ACTIVE'?'Close':'Activate')))]);
  Widget pledgeList()=>ListView(padding:const EdgeInsets.all(16),children:[header('Pledges'),if(pledges.isEmpty)empty('No pledges found.')else for(final p in pledges)card(money(p['pledgedAmountPaise'])+' pledge','Campaign '+s(p['campaignId'])+'\nPaid '+money(p['paidAmountPaise'])+' • '+s(p['status']),Icons.favorite_outline,action:IconButton(onPressed:busy?null:()=>record(p),tooltip:'Record payment',icon:const Icon(Icons.add_card)))]);
  Widget paymentList()=>ListView(padding:const EdgeInsets.all(16),children:[header('Payments'),if(payments.isEmpty)empty('No payments found.')else for(final p in payments)card(money(p['amountPaise'])+' • '+s(p['method']),s(p['status'])+' • Pledge '+s(p['pledgeId']),Icons.payments_outlined,action:p['status']=='PENDING_APPROVAL'?PopupMenuButton<String>(onSelected:(v)=>v=='approve'?review('/api/giving/payments/'+s(p['id'])+'/approve'):reject('/api/giving/payments/'+s(p['id'])+'/reject'),itemBuilder:(_)=>const[PopupMenuItem(value:'approve',child:Text('Verify')),PopupMenuItem(value:'reject',child:Text('Reject'))]):p['status']=='VERIFIED'?IconButton(onPressed:busy?null:()=>adjust(p),tooltip:'Refund / reversal',icon:const Icon(Icons.undo)):null)]);
  Widget expenseList()=>ListView(padding:const EdgeInsets.all(16),children:[header('Expenses',action:FilledButton.icon(onPressed:busy?null:expense,icon:const Icon(Icons.add),label:const Text('Record'))),if(expenses.isEmpty)empty('No expenses found.')else for(final e in expenses)card(s(e['category'])+' • '+money(e['amountPaise']),s(e['description'])+' • '+s(e['status']),Icons.receipt_long_outlined,action:e['status']=='PENDING_APPROVAL'?PopupMenuButton<String>(onSelected:(v)=>v=='approve'?review('/api/giving/expenses/'+s(e['id'])+'/approve'):reject('/api/giving/expenses/'+s(e['id'])+'/reject'),itemBuilder:(_)=>const[PopupMenuItem(value:'approve',child:Text('Approve')),PopupMenuItem(value:'reject',child:Text('Reject'))]):null)]);
  Widget adjustmentList()=>ListView(padding:const EdgeInsets.all(16),children:[header('Refunds and reversals'),if(adjustments.isEmpty)empty('No requests found.')else for(final a in adjustments)card(s(a['kind'])+' • '+money(a['amountPaise']),s(a['reason'])+' • '+s(a['status']),Icons.currency_exchange,action:a['status']=='PENDING_APPROVAL'?PopupMenuButton<String>(onSelected:(v)=>v=='approve'?review('/api/giving/adjustments/'+s(a['id'])+'/approve'):reject('/api/giving/adjustments/'+s(a['id'])+'/reject'),itemBuilder:(_)=>const[PopupMenuItem(value:'approve',child:Text('Approve')),PopupMenuItem(value:'reject',child:Text('Reject'))]):null)]);
  Widget receiptList()=>ListView(padding:const EdgeInsets.all(16),children:[header('Issued receipts'),if(receipts.isEmpty)empty('No receipts found.')else for(final r in receipts)card(s(r['receiptNumber'],'Receipt'),money(r['amountPaise'])+' • '+s(r['method'])+' • '+s(r['issuedAt']??r['createdAt']),Icons.receipt_outlined)]);
  Widget reconList(){final a=Map<String,dynamic>.from((recon['adjustments'] as Map?)??const{});return ListView(padding:const EdgeInsets.all(16),children:[header('Reconciliation'),const Text('Operational control report only; it does not confirm bank settlement or replace a double-entry ledger.'),card('Verified payments',money(recon['verifiedPaymentAmountPaise']??recon['receivedAmountPaise']),Icons.payments_outlined),card('Approved expenses',money(recon['approvedExpenseAmountPaise']),Icons.receipt_long_outlined),card('Approved adjustments',money(a['approvedAmountPaise']),Icons.currency_exchange),card('Net after expenses and adjustments',money(recon['netAfterApprovedExpensesAndAdjustmentsPaise']),Icons.account_balance),card('Receipt discrepancies',((recon['receiptDiscrepancies'] as List?)?.length??0).toString(),Icons.fact_check_outlined)]);}
}